version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: ./backend
    image: nodeserver:1.0
    container_name: node_container
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/orders?authSource=admin
    depends_on:
      - mongodb
